package presentacion;

import dtos.UsuarioDTO;
import javax.swing.JOptionPane;
import obtenerUsuarios.FObtenerUsuarios;
import obtenerUsuarios.IObtenerUsuarios;
import registrarUsuario.FRegistrarUsuario;
import registrarUsuario.IRegistrarUsuario;

/**
 *
 * @author af_da
 */
public class LoginUsuario extends javax.swing.JFrame {

    private IObtenerUsuarios obtenerUsuario;

    /**
     * Creates new form LoginUsuario
     */
    public LoginUsuario() {
        initComponents();
        obtenerUsuario = new FObtenerUsuarios();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnRegistro = new javax.swing.JButton();
        txtContra = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 230, -1));

        btnRegistro.setText("Registro");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));
        getContentPane().add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 230, -1));

        jLabel3.setText("FITNESS APP");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 400, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        RegistroUsuario registro = new RegistroUsuario();
        registro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if (ValidarInicio()) {
            Menu menu = new Menu();
            menu.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_btnIngresarActionPerformed

    private boolean ValidarInicio() {
        if (!this.txtUsuario.getText().isBlank()) {
            if (!this.txtContra.getText().isBlank()) {
                String usuario = txtUsuario.getText();
                String contra = String.valueOf(txtContra.getPassword());
                UsuarioDTO usuarioDTO = new UsuarioDTO(null, "", usuario, contra, 0, 0f, 0f);
                UsuarioDTO usuarioConsultado = this.obtenerUsuario.obtenerUsuario(usuarioDTO);
                if (usuarioConsultado == null) {
                    JOptionPane.showMessageDialog(this, "No se encontro el usuario");
                } else {
                    SeguimientoEjercicioPresentacion.USUARIO = usuarioConsultado;
                    return true;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Llenar el campo de contraseña");
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Llenar el campo de usuario");
            return false;
        }
        
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
