package presentacion;

import dtos.EjercicioDiarioDTO;
import dtos.RutinaDTO;
import dtos.UsuarioDTO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import negocio.IRutinaBO;
import negocio.IUsuarioBO;
import negocio.RutinaBO;
import negocio.UsuariosBO;

/**
 *
 * @author af_da
 */
public class Menu extends javax.swing.JFrame {
    
    private IRutinaBO rNegocio;
    private IUsuarioBO uNegocio;
    private DefaultTableModel modeloTabla;
    private UsuarioDTO usuario;
    private String[] dias = {"TODOS", "LUNES", "MARTES", "MIERCOLES", "JUEVES", "VIERNES", "SABADO", "DOMINGO"};

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        rNegocio = new RutinaBO();
        uNegocio = new UsuariosBO();
        this.usuario = uNegocio.loginUsuario(SeguimientoEjercicioPresentacion.USUARIO);
        modeloTabla = new DefaultTableModel(new String[]{"Día", "Ejercicio", "Tipo", "Tiempo", "Estado"}, 0);
        tablaEjercicios.setModel(modeloTabla); // Asigna el modelo a la tabla
        llenarComboBoxDias(); // Llenar el JComboBox
        llenarTabla(null); // Llenar la tabla al iniciar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnAgregarEjercicio = new javax.swing.JButton();
        btnModificarEjercicio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEjercicios = new javax.swing.JTable();
        btnEliminarEjercicio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbxFiltroDias = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregarEjercicio.setText("Agregar Ejercicio");
        btnAgregarEjercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEjercicioActionPerformed(evt);
            }
        });

        btnModificarEjercicio.setText("Modificar Ejercicio");

        tablaEjercicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Dia", "Ejercicio", "Tipo", "Tiempo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaEjercicios);

        btnEliminarEjercicio.setText("Eliminar Ejercicio");

        jLabel1.setText("Filtrar por dia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addComponent(btnModificarEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarEjercicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxFiltroDias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregarEjercicio)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarEjercicio)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarEjercicio)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxFiltroDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llenarComboBoxDias() {
        for (String dia : dias) {
            cbxFiltroDias.addItem(dia);
        }
        
        cbxFiltroDias.addActionListener(evt -> {
            String diaSeleccionado = (String) cbxFiltroDias.getSelectedItem();
            if ("TODOS".equals(diaSeleccionado)) {
                llenarTabla(null); // Mostrar todos los ejercicios
            } else {
                llenarTabla(diaSeleccionado); // Filtrar por el día seleccionado
            }
        });
    }
    
    public void llenarTabla(String diaFiltro) {
        List<RutinaDTO> rutinas = rNegocio.obtenerRutinas(usuario);
        modeloTabla.setRowCount(0); // Limpia la tabla

        for (RutinaDTO rutina : rutinas) {
            if (diaFiltro == null || rutina.dia().nombre().equals(diaFiltro)) {
                for (EjercicioDiarioDTO ejercicio : rutina.ejerciciosDiarios()) {
                    Object[] fila = new Object[]{
                        rutina.dia().nombre(),
                        ejercicio.ejercicio().nombre(),
                        ejercicio.ejercicio().tipo(),
                        ejercicio.ejercicio().duracion(),
                        ejercicio.completado() ? "Completado" : "No completado"
                    };
                    modeloTabla.addRow(fila);
                }
            }
        }

        modeloTabla.fireTableDataChanged();
    }
    
    private void btnAgregarEjercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEjercicioActionPerformed
        RegistroEjercicio registroEjercicio = new RegistroEjercicio();
        registroEjercicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarEjercicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEjercicio;
    private javax.swing.JButton btnEliminarEjercicio;
    private javax.swing.JButton btnModificarEjercicio;
    private javax.swing.JComboBox<String> cbxFiltroDias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaEjercicios;
    // End of variables declaration//GEN-END:variables
}
