package presentacion;

import dtos.UsuarioDTO;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import obtenerRutinas.FObtenerRutinas;
import obtenerUsuarios.FObtenerUsuarios;
import obtenerUsuarios.IObtenerUsuarios;
import rankingUsuarios.FRankingUsuario;
import rankingUsuarios.IRankingUsuario;

/**
 *
 * @author alex_
 */
public class RankingUsuarios extends javax.swing.JFrame {

    private IRankingUsuario negocio;
    private DefaultTableModel modeloTablaRanking;
    private IObtenerUsuarios obtenerUsuario;
    private UsuarioDTO usuario;
    
    /**
     * Creates new form RankingUsuarios
     */
    public RankingUsuarios() {
        initComponents();
        negocio = new FRankingUsuario();
        obtenerUsuario = new FObtenerUsuarios();
        this.usuario = obtenerUsuario.obtenerUsuario(SeguimientoEjercicioPresentacion.USUARIO);
        modeloTablaRanking = new DefaultTableModel(new String[]{"Nombre", "Ejercicios Totales", "Ejercicios Completados", "Porcentaje"}, 0);
        tblRanking.setModel(modeloTablaRanking);
        llenarTablaRanking(negocio.obtenerRanking(usuario));
    }
    
    private void llenarTablaRanking(Map<String, Object> ranking) {
        modeloTablaRanking.setRowCount(0);

        ranking.forEach((nombre, datos) -> {
            // Realizar el cast explícito de Object a Object[]
            Object[] datosArray = (Object[]) datos;

            Object[] fila = new Object[]{
                nombre,
                datosArray[0], // Total ejercicios
                datosArray[1], // Ejercicios completados
                datosArray[2] // Porcentaje
            };
            modeloTablaRanking.addRow(fila);
        });

        modeloTablaRanking.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRanking = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ranking de usuarios Semanal");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        tblRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRanking);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 440, 240));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRanking;
    // End of variables declaration//GEN-END:variables
}
