/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dtos.EjercicioDTO;
import dtos.EjercicioDiarioDTO;
import dtos.RutinaDTO;
import dtos.UsuarioDTO;
import negocio.DiaBO;
import negocio.EjercicioBO;
import negocio.EjercicioDiarioBO;
import negocio.IDiaBO;
import negocio.IEjercicioBO;
import negocio.IEjercicioDiarioBO;
import negocio.IRutinaBO;
import negocio.RutinaBO;

/**
 *
 * @author af_da
 */
public class RegistroEjercicio extends javax.swing.JFrame {
    private IEjercicioBO ejercicioBO;
    private IRutinaBO rutinaBO;
    private IEjercicioDiarioBO ejercicioDiarioBO;
    private IDiaBO diaBO;
    private UsuarioDTO usuario = SeguimientoEjercicioPresentacion.USUARIO;

    /**
     * Creates new form RegistroEjercicio
     */
    public RegistroEjercicio() {
        initComponents();
        ejercicioBO = new EjercicioBO();    
        rutinaBO = new RutinaBO();
        diaBO = new DiaBO();
        ejercicioDiarioBO = new EjercicioDiarioBO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        checkLunes = new javax.swing.JCheckBox();
        checkMartes = new javax.swing.JCheckBox();
        checkMiercoles = new javax.swing.JCheckBox();
        checkJueves = new javax.swing.JCheckBox();
        checkViernes = new javax.swing.JCheckBox();
        checkSabado = new javax.swing.JCheckBox();
        checkDomingo = new javax.swing.JCheckBox();
        btnCrear = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setText("Crear ejercicio");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel3.setText("Tipo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel4.setText("Duración:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 240, -1));
        getContentPane().add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 240, -1));
        getContentPane().add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 240, -1));

        checkLunes.setText("Lunes");
        getContentPane().add(checkLunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        checkMartes.setText("Martes");
        getContentPane().add(checkMartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        checkMiercoles.setText("Miercoles");
        getContentPane().add(checkMiercoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        checkJueves.setText("Jueves");
        getContentPane().add(checkJueves, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        checkViernes.setText("Viernes");
        getContentPane().add(checkViernes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        checkSabado.setText("Sabado");
        getContentPane().add(checkSabado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        checkDomingo.setText("Domingo");
        checkDomingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDomingoActionPerformed(evt);
            }
        });
        getContentPane().add(checkDomingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 272, -1, -1));

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel5.setText("Dias de ejercicio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 40, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkDomingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDomingoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkDomingoActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        EjercicioDTO ejercicioCreado = this.crearEjercicio();
        
        boolean lunesSeleccionado = checkLunes.isSelected();
        boolean martesSeleccionado = checkMartes.isSelected();
        boolean miercolesSeleccionado = checkMiercoles.isSelected();
        boolean juevesSeleccionado = checkJueves.isSelected();
        boolean viernesSeleccionado = checkViernes.isSelected();
        boolean sabadoSeleccionado = checkSabado.isSelected();
        boolean domingoSeleccionado = checkDomingo.isSelected();
        
        System.out.println(ejercicioCreado);
        
        // Lunes
        if (checkLunes.isSelected()) {
            RutinaDTO rutinaDtoLunes = rutinaBO.obtenerRutina(usuario, diaBO.obtenerNumeroDia("Lunes"));
            EjercicioDiarioDTO ejercicioDiarioDTO = new EjercicioDiarioDTO(-1L, ejercicioCreado, false, rutinaDtoLunes);
            ejercicioDiarioBO.crearEjercicioDiario(ejercicioDiarioDTO);
        }

        // Martes
        if (checkMartes.isSelected()) {
            RutinaDTO rutinaDtoMartes = rutinaBO.obtenerRutina(usuario, diaBO.obtenerNumeroDia("Martes"));
            EjercicioDiarioDTO ejercicioDiarioDTO = new EjercicioDiarioDTO(-1L, ejercicioCreado, false, rutinaDtoMartes);
            ejercicioDiarioBO.crearEjercicioDiario(ejercicioDiarioDTO);
        }

        // Miércoles
        if (checkMiercoles.isSelected()) {
            RutinaDTO rutinaDtoMiercoles = rutinaBO.obtenerRutina(usuario, diaBO.obtenerNumeroDia("Miércoles"));
            EjercicioDiarioDTO ejercicioDiarioDTO = new EjercicioDiarioDTO(-1L, ejercicioCreado, false, rutinaDtoMiercoles);
            ejercicioDiarioBO.crearEjercicioDiario(ejercicioDiarioDTO);
        }

        // Jueves
        if (checkJueves.isSelected()) {
            RutinaDTO rutinaDtoJueves = rutinaBO.obtenerRutina(usuario, diaBO.obtenerNumeroDia("Jueves"));
            EjercicioDiarioDTO ejercicioDiarioDTO = new EjercicioDiarioDTO(-1L, ejercicioCreado, false, rutinaDtoJueves);
            ejercicioDiarioBO.crearEjercicioDiario(ejercicioDiarioDTO);
        }

        // Viernes
        if (checkViernes.isSelected()) {
            RutinaDTO rutinaDtoViernes = rutinaBO.obtenerRutina(usuario, diaBO.obtenerNumeroDia("Viernes"));
            EjercicioDiarioDTO ejercicioDiarioDTO = new EjercicioDiarioDTO(-1L, ejercicioCreado, false, rutinaDtoViernes);
            ejercicioDiarioBO.crearEjercicioDiario(ejercicioDiarioDTO);
        }

        // Sábado
        if (checkSabado.isSelected()) {
            RutinaDTO rutinaDtoSabado = rutinaBO.obtenerRutina(usuario, diaBO.obtenerNumeroDia("Sábado"));
            EjercicioDiarioDTO ejercicioDiarioDTO = new EjercicioDiarioDTO(-1L, ejercicioCreado, false, rutinaDtoSabado);
            ejercicioDiarioBO.crearEjercicioDiario(ejercicioDiarioDTO);
        }

        // Domingo
        if (checkDomingo.isSelected()) {
            RutinaDTO rutinaDtoDomingo = rutinaBO.obtenerRutina(usuario, diaBO.obtenerNumeroDia("Domingo"));
            EjercicioDiarioDTO ejercicioDiarioDTO = new EjercicioDiarioDTO(-1L, ejercicioCreado, false, rutinaDtoDomingo);
            ejercicioDiarioBO.crearEjercicioDiario(ejercicioDiarioDTO);
        }
        Menu menu = new Menu();
        menu.llenarTabla(null);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    private EjercicioDTO crearEjercicio(){
        String nombre = txtNombre.getText();
        String tipo = txtTipo.getText();
        String duracion = txtDuracion.getText();
        EjercicioDTO ejercicioDTO = new EjercicioDTO(-1L, nombre, tipo, Float.parseFloat(duracion));
        return ejercicioBO.crearEjercicio(ejercicioDTO);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JCheckBox checkDomingo;
    private javax.swing.JCheckBox checkJueves;
    private javax.swing.JCheckBox checkLunes;
    private javax.swing.JCheckBox checkMartes;
    private javax.swing.JCheckBox checkMiercoles;
    private javax.swing.JCheckBox checkSabado;
    private javax.swing.JCheckBox checkViernes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
